
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./mycomponents/Navbar";
import Footer from "./mycomponents/footer";



const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        <div className="lg:w-[1440px] mx-auto ">
          <Navbar/>
        {children}
        <Footer/>
        </div>
      </body>
    </html>
  );
}
